"""initial schema

Revision ID: b8c21c62d5f3
Revises: 
Create Date: 2026-09-17 06:43:44.790726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c21c62d5f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_table('question_bank_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round', sa.Enum('PYTHON', 'MACHINE_LEARNING', 'NLP', 'SCENARIO', 'HR', name='bankround', native_enum=False), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('subtopic', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('expected_concepts', sa.JSON(), nullable=False),
    sa.Column('followup_hints', sa.JSON(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_bank_items'))
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=True),
    sa.Column('target_role', sa.String(length=100), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'INTRODUCTION', 'PYTHON', 'MACHINE_LEARNING', 'NLP', 'PROJECT_DISCUSSION', 'SCENARIO', 'HR', 'COMPLETED', 'TERMINATED', name='sessionstate', native_enum=False), nullable=False),
    sa.Column('current_difficulty', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_interview_sessions_candidate_id_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_sessions'))
    )
    op.create_table('coach_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_coach_conversations_session_id_interview_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_conversations'))
    )
    op.create_table('difficulty_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('previous_difficulty', sa.Integer(), nullable=False),
    sa.Column('new_difficulty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('STRONG_ANSWER', 'WEAK_ANSWER', 'AVERAGE_ANSWER', name='difficultychangereason', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_difficulty_log_session_id_interview_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_difficulty_log'))
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_bank_item_id', sa.Uuid(), nullable=True),
    sa.Column('parent_question_id', sa.Uuid(), nullable=True),
    sa.Column('round', sa.Enum('INTRODUCTION', 'PYTHON', 'MACHINE_LEARNING', 'NLP', 'PROJECT_DISCUSSION', 'SCENARIO', 'HR', name='questionround', native_enum=False), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('BANK', 'FOLLOW_UP', 'PROJECT', 'SCENARIO', 'BEHAVIORAL', 'INTRO', name='questiontype', native_enum=False), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_question_id'], ['interview_questions.id'], name=op.f('fk_interview_questions_parent_question_id_interview_questions')),
    sa.ForeignKeyConstraint(['question_bank_item_id'], ['question_bank_items.id'], name=op.f('fk_interview_questions_question_bank_item_id_question_bank_items')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_questions_session_id_interview_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_questions'))
    )
    op.create_table('interview_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('category_scores', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('improvements', sa.JSON(), nullable=False),
    sa.Column('recruiter_summary', sa.Text(), nullable=False),
    sa.Column('learning_roadmap', sa.JSON(), nullable=False),
    sa.Column('readiness_level', sa.Enum('NOT_READY', 'DEVELOPING', 'READY', 'STRONG', name='readinesslevel', native_enum=False), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('fk_interview_reports_session_id_interview_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_reports')),
    sa.UniqueConstraint('session_id', name=op.f('uq_interview_reports_session_id'))
    )
    op.create_table('candidate_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_question_id', sa.Uuid(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('answer_duration_seconds', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_question_id'], ['interview_questions.id'], name=op.f('fk_candidate_answers_interview_question_id_interview_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_answers')),
    sa.UniqueConstraint('interview_question_id', name=op.f('uq_candidate_answers_interview_question_id'))
    )
    op.create_table('coach_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('referenced_question_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['coach_conversations.id'], name=op.f('fk_coach_messages_conversation_id_coach_conversations')),
    sa.ForeignKeyConstraint(['referenced_question_id'], ['interview_questions.id'], name=op.f('fk_coach_messages_referenced_question_id_interview_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_messages'))
    )
    op.create_table('answer_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_answer_id', sa.Uuid(), nullable=False),
    sa.Column('technical_accuracy', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Integer(), nullable=False),
    sa.Column('completeness', sa.Integer(), nullable=False),
    sa.Column('communication_clarity', sa.Integer(), nullable=False),
    sa.Column('concept_coverage', sa.Integer(), nullable=False),
    sa.Column('composite_score', sa.Integer(), nullable=False),
    sa.Column('evaluator_reasoning', sa.Text(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_answer_id'], ['candidate_answers.id'], name=op.f('fk_answer_evaluations_candidate_answer_id_candidate_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_evaluations')),
    sa.UniqueConstraint('candidate_answer_id', name=op.f('uq_answer_evaluations_candidate_answer_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_evaluations')
    op.drop_table('coach_messages')
    op.drop_table('candidate_answers')
    op.drop_table('interview_reports')
    op.drop_table('interview_questions')
    op.drop_table('difficulty_log')
    op.drop_table('coach_conversations')
    op.drop_table('interview_sessions')
    op.drop_table('question_bank_items')
    op.drop_table('candidates')
    # ### end Alembic commands ###
